# Generated by Django 3.1 on 2020-09-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='physique',
            name='link',
            field=models.URLField(),
        ),
    ]
