# Generated by Django 3.1.1 on 2020-09-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practices', '0002_auto_20200906_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('link', models.URLField()),
                ('slug', models.SlugField()),
                ('thumb', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='diet',
        ),
        migrations.DeleteModel(
            name='Meditation',
        ),
        migrations.DeleteModel(
            name='physique',
        ),
    ]
