# Generated by Django 3.1.1 on 2020-09-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practices', '0003_auto_20200909_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practices',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
