# Generated by Django 3.1.1 on 2020-09-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practices', '0004_auto_20200909_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practices',
            name='link',
        ),
        migrations.AlterField(
            model_name='practices',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
