# Generated by Django 3.1.1 on 2020-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practices', '0005_auto_20200910_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practices',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
