# Generated by Django 3.1 on 2020-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practices', '0008_auto_20200911_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practices',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='practices',
            name='u_rl',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
